title: Anh H Nguyen
description: Data-Driven Solutions · Strategic Leadership · Supply Chain Innovation
logo: <img src="/assets/Anh2.png" alt="My profile picture" style="width: 150px; border-radius: 50%;">
theme: jekyll-theme-leap-day

include:
  - assets/css

